version: '3'

services:
  pandoratokentool:
    image: kwxos/pandoratokentool:latest
    container_name: pandoratokentool
    restart: always
    network_mode: host
    environment:
      - new=1
      - PT_PORT=8081
      - Pdlport=8181
      - proxy_api_prefix=wxosler
      - setup_password=kwxosjyancan.
      - licid=yxxxxxevjZxxxFg9xxxxxE
    volumes:
      - ./PandoraNextToken:/data
