version: '3'

services:
  pandoratokentool:
    image: kwxos/pandoratokentool:latestvps
    container_name: pandoratokentool
    restart: always
    network_mode: host
    environment:
      - new=1
      - PT_PORT=8081
      - Pdlport=8181
      - licid=YDD_kJm32OwaB4kpA4wecMgE8hJNMY7W54on8711QJQ
      - Tool_path=/tokensTool
    volumes:
      - ./PandoraNextToken:/data
